//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLN_Resource
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Tel { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public int ResourceProvince { get; set; }
        public int ResourceCity { get; set; }
        public Nullable<int> ResourceServiceM { get; set; }
        public Nullable<int> ResourceServiceD { get; set; }
        public string Type2 { get; set; }
        public string Type3 { get; set; }
        public string Company { get; set; }
        public Nullable<int> BussinessRule { get; set; }
        public System.DateTime PostTime { get; set; }
        public string PostIP { get; set; }
        public System.DateTime LastModTime { get; set; }
        public int Reads { get; set; }
        public int IsLock { get; set; }
        public int Comments { get; set; }
        public string MD5 { get; set; }
        public string Content { get; set; }
        public int ChildType { get; set; }
        public int FromType { get; set; }
        public string FromData { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
    }
}
