//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLN_GroupDiscuss
    {
        public int id { get; set; }
        public int GroupId { get; set; }
        public int UserId { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Company { get; set; }
        public string Content { get; set; }
        public int Type { get; set; }
        public int CommentID { get; set; }
    }
}
