//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLN_Group
    {
        public int Id { get; set; }
        public string GroupName { get; set; }
        public string GroupNameEn { get; set; }
        public int IsOpen { get; set; }
        public int Peoples { get; set; }
        public string Rights { get; set; }
        public int px { get; set; }
        public string Discription { get; set; }
        public string DiscriptionEn { get; set; }
        public string Introduce { get; set; }
        public string IntroduceEn { get; set; }
        public int CoopSubmitCount { get; set; }
    }
}
