//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_APP_Webtool
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int IndustryID { get; set; }
        public int ServiceID { get; set; }
        public int ProvinceID { get; set; }
        public int CityID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Url { get; set; }
        public int ReadCount { get; set; }
        public int HotValue { get; set; }
        public int Type { get; set; }
        public System.DateTime Addtime { get; set; }
    }
}
