//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_ClnMessage
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> SendId { get; set; }
        public int Flag { get; set; }
        public System.DateTime AddTime { get; set; }
        public bool isRead { get; set; }
        public Nullable<int> TitleId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string ContentEn { get; set; }
    }
}
