//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_ClnMsgAdvLink
    {
        public int Id { get; set; }
        public string Href { get; set; }
        public string InnerText { get; set; }
        public string InnerTextEn { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public int Flag { get; set; }
        public System.DateTime AddTime { get; set; }
        public bool Enable { get; set; }
    }
}
