//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_CardDrawText
    {
        public int ID { get; set; }
        public int TemplateID { get; set; }
        public string Title { get; set; }
        public string TitleEN { get; set; }
        public string DefaultValue { get; set; }
        public string DefaultValueEN { get; set; }
        public string FamliyName { get; set; }
        public int FontStyle { get; set; }
        public int FontSize { get; set; }
        public int BackgroundColor { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public bool Warp { get; set; }
        public int FontColor { get; set; }
        public System.DateTime AddTime { get; set; }
        public int TextLayout { get; set; }
    }
}
