//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_GroupCompany
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public string Company { get; set; }
        public string CompanyEn { get; set; }
        public string ShortName { get; set; }
        public string ShortNameEn { get; set; }
        public string Phone { get; set; }
        public string Introduce { get; set; }
        public string IntroduceEn { get; set; }
        public string Url { get; set; }
        public string Logo { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool DelFlag { get; set; }
        public int PX { get; set; }
    }
}
