//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_InformationScore
    {
        public int InformationId { get; set; }
        public int GoodCount { get; set; }
        public int BadCount { get; set; }
        public int AvgCount { get; set; }
        public int GoodSum { get; set; }
        public int BadSum { get; set; }
        public int AvgSum { get; set; }
        public int Score { get; set; }
    }
}
