//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_LeadMan
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Web { get; set; }
        public string Summary { get; set; }
        public Nullable<int> Province { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> CN_Place { get; set; }
        public Nullable<int> CN_Places { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Type { get; set; }
        public int Integral { get; set; }
        public int px { get; set; }
    }
}
