//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_MarketData
    {
        public int UserId { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int EmailsCount { get; set; }
        public int MobilesCount { get; set; }
        public int FaxsCount { get; set; }
        public string Emails { get; set; }
        public string Mobiles { get; set; }
        public string Faxs { get; set; }
    }
}
