//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_OnlineUser
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string LastIP { get; set; }
        public string LastUrl { get; set; }
        public Nullable<System.DateTime> LastTime { get; set; }
        public string UserName { get; set; }
    }
}
