//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_OutFriend
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string Company { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string MSN { get; set; }
        public string QQ { get; set; }
        public string SKYPE { get; set; }
        public string Address { get; set; }
        public string Remark { get; set; }
        public string CompanyUrl { get; set; }
        public int Type { get; set; }
        public int CustormType { get; set; }
        public int RegUserID { get; set; }
    }
}
