//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_SpaceTemplate
    {
        public int ID { get; set; }
        public string TName { get; set; }
        public string TPath { get; set; }
        public System.DateTime CreatTime { get; set; }
        public string TPicture { get; set; }
        public byte IsLock { get; set; }
        public Nullable<int> IPoint { get; set; }
        public Nullable<int> GPoint { get; set; }
        public Nullable<byte> isBG { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> UserNumber { get; set; }
    }
}
