//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_Shop
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Price1 { get; set; }
        public string Discount { get; set; }
        public Nullable<System.DateTime> PostTime { get; set; }
        public string PostIP { get; set; }
        public Nullable<bool> IsLock { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> BigServiceId { get; set; }
        public Nullable<int> SmallServiceId { get; set; }
        public int Remarks { get; set; }
        public int Reads { get; set; }
        public int Concern { get; set; }
        public int Price { get; set; }
        public int Type { get; set; }
        public Nullable<int> FileId { get; set; }
        public int DocumentType { get; set; }
        public string FileIdArray { get; set; }
        public int LanguageID { get; set; }
        public string SimilarArray { get; set; }
        public string TopicIDList { get; set; }
        public Nullable<bool> IsTop { get; set; }
    }
}
