//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_SmtpMailPool
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Host { get; set; }
        public int Port { get; set; }
        public int Flag { get; set; }
        public int ErrorCount { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool EnableSSL { get; set; }
        public bool Enable { get; set; }
        public string DisplayName { get; set; }
        public int OnceCount { get; set; }
    }
}
