//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_User
    {
        public int UserID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public int UserGender { get; set; }
        public int UserAge { get; set; }
        public string UserCompName { get; set; }
        public string UserCompAddr { get; set; }
        public string UserCompTel { get; set; }
        public string UserCompFax { get; set; }
        public string UserMobile { get; set; }
        public string UserWeb { get; set; }
        public string UserMSN { get; set; }
        public string UserQQ { get; set; }
        public string UserSKYPE { get; set; }
        public string UserJob { get; set; }
        public string UserDiscount { get; set; }
        public int UserService { get; set; }
        public int UserServices1 { get; set; }
        public int UserServices2 { get; set; }
        public int UserServices3 { get; set; }
        public int UserServices4 { get; set; }
        public int UserServices5 { get; set; }
        public int UserLanguage1 { get; set; }
        public int UserLanguage2 { get; set; }
        public int UserLanguage3 { get; set; }
        public string UserPro { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string LastLoginIP { get; set; }
        public int LoginTimes { get; set; }
        public int Province { get; set; }
        public int City { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public string RegIP { get; set; }
        public Nullable<int> Portrait { get; set; }
        public Nullable<int> InviterID { get; set; }
        public string VerifyCode { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public Nullable<bool> Recommended { get; set; }
        public Nullable<int> integral { get; set; }
        public Nullable<int> inteyb { get; set; }
        public Nullable<int> Kid { get; set; }
        public Nullable<int> Click { get; set; }
        public bool IsVip { get; set; }
        public int UserType { get; set; }
        public int FriendPlaces { get; set; }
        public int OutFriends { get; set; }
        public int ClnCurrency { get; set; }
    }
}
