//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_UserPointHistory
    {
        public int id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Content { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<int> GPoint { get; set; }
        public Nullable<byte> UTF { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
    }
}
