//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_UserInfo
    {
        public int UserID { get; set; }
        public bool Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> BirthidayDisplay { get; set; }
        public Nullable<int> Constellation { get; set; }
        public string MSN { get; set; }
        public string GTalk { get; set; }
        public string QQ { get; set; }
        public string Skype { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> MobilePrivacy { get; set; }
        public Nullable<int> EmailPrivacy { get; set; }
        public string Tel { get; set; }
        public string Addr { get; set; }
        public string WebSite { get; set; }
        public string Favourite { get; set; }
        public string FavMusics { get; set; }
        public string FavMovies { get; set; }
        public string FavCartoons { get; set; }
        public string FavGames { get; set; }
        public string FavSports { get; set; }
        public string FavBooks { get; set; }
        public string FavAdages { get; set; }
        public string AppreciateMen { get; set; }
        public string Presentation { get; set; }
        public Nullable<int> Vocation { get; set; }
        public Nullable<int> HomeProv { get; set; }
        public Nullable<int> HomeCity { get; set; }
        public Nullable<int> MSNPrivacy { get; set; }
        public Nullable<int> GTalkPrivacy { get; set; }
        public Nullable<int> QQPrivacy { get; set; }
        public Nullable<int> SkypePrivacy { get; set; }
        public Nullable<int> TelPrivacy { get; set; }
        public Nullable<int> AddrPrivacy { get; set; }
        public Nullable<int> WebSitePrivacy { get; set; }
    }
}
