//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_UserSetting
    {
        public int UserID { get; set; }
        public int PrivSpace { get; set; }
        public int PrivFavourite { get; set; }
        public int PrivEducate { get; set; }
        public int PrivLasso { get; set; }
        public int PrivFriends { get; set; }
        public int PrivLeaveWord { get; set; }
        public int PrivMiniBlog { get; set; }
        public int PrivShare { get; set; }
        public int PrivGroup { get; set; }
        public int PrivMovies { get; set; }
        public bool ActUpdateData { get; set; }
        public bool ActAddFriend { get; set; }
        public bool ActLeaveWord { get; set; }
        public bool ActPicComment { get; set; }
        public bool ActSecede { get; set; }
        public bool ActDeliver { get; set; }
        public bool ActLogComment { get; set; }
        public bool ActMovieComment { get; set; }
        public bool ActPhotoLasso { get; set; }
        public bool ActShareComment { get; set; }
        public System.DateTime LastPostTime { get; set; }
        public string LastPostIP { get; set; }
    }
}
