//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opensocial_activity_media_items
    {
        public int id { get; set; }
        public int activity_id { get; set; }
        public string mime_type { get; set; }
        public string media_type { get; set; }
        public string url { get; set; }
    }
}
