//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFForMSsql
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_errorlog
    {
        public int id { get; set; }
        public string errorlog { get; set; }
        public Nullable<System.DateTime> errorTime { get; set; }
        public string ErrorUrl { get; set; }
        public string ErrorIP { get; set; }
        public Nullable<int> ErrorLevel { get; set; }
    }
}
